name: ci-reproducibility

on:
  push:
    branches:
      - ci
      - dev
      - main
  pull_request:
    branches: [ main ]

  # Besides pushes on the branches above, also check every day at 00:00 UTC.
  schedule:
    - cron: "0 0 * * *"

  # Allows running the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_fortanix-sgx-tools:
    name: check-reproducibility
    runs-on: ubuntu-latest
    env:
      elf2sgxs_hash: "411d70e17634d6ad54dcc7dbf40f61fab5dfc9626fd8120ce9fd2063561f44d5"
      runner_hash: "c5437c2bd13fbe2806ea51fd4c97e993d848ee86960302888b33319065e1a38c"
      runner_cargo_hash: "a4775959992cb69ceb943c5374d54dbe077912763dbb9ff324f35a16f1a8d531"
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v16
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.7.0pre20220225_fd4b693/install
      - name: Install cachix
        uses: cachix/cachix-action@v10
        with:
          name: initc3
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix --version
      - run: nix build
      - run: nix build --rebuild
      - run: nix flake check
      - run: nix flake metadata
      - run: nix flake show
      - run: ls -l result

      # TODO: Implement action to check the hash
      - run: sha256sum result/bin/*
      - name: Shasum check ftxsgx-elf2sgxs
        run: |
          echo "$elf2sgxs_hash *result/bin/ftxsgx-elf2sgxs" | \
            shasum --algorithm 512256 --binary --strict --check
      - name: Shasum check ftxsgx-runner
        run: |
          echo "$runner_hash *result/bin/ftxsgx-runner" | \
            shasum --algorithm 512256 --binary --strict --check
      - name: Shasum check ftxsgx-runner-cargo
        run: |
          echo "$runner_cargo_hash *result/bin/ftxsgx-runner-cargo" | \
            shasum --algorithm 512256 --binary --strict --check
